### ISSUE TITLE
installation compilation error 

### ISSUE THREAD

**Issue by ryao-mdanderson** [MonashBioinformaticsPlatform/provean#3]
Dear provean author,

I followed the instruction, try to install provean 1.1.5 on RHEL 8.7 HPC cluster. I have the prerequisite versions as 
  NCBI blast 2.16.0+ 
  CD-Hit 4.8.1
 configured with 
  $ cd /risapps/rhel8/provean/1.1.5
        ./configure --prefix=/risapps/rhel8/provean/1.1.5 \
          BLAST_DB=/rsrch3/scratch/reflib/REFLIB_data/blast_db/nr-database-data/ \
          PSIBLAST=/risapps/rhel8/blast/2.16.0+/bin \
          CDHIT=/risapps/rhel8/cdhit/4.8.1 \
          BLASTDBCMD=/risapps/rhel8/blast/2.16.0+/bin

 $ make

     I  tried different gcc compile gcc/11.3.0 , gcc/9.3.0 gcc/8.5.0
      all hit the error message
         CDPATH="${ZSH_VERSION+.}:" && cd . && aclocal-1.13 
        /bin/sh: aclocal-1.13: command not found
         make: *** [Makefile:320: aclocal.m4] Error 127

I had ncbi 2.4.0 installed as well, while change PSIBLAST=/risapps/rhel8/blast/2.4.0+/bin, the make output error message is:
  cd . && automake-1.13 --foreign
/bin/sh: line 4: automake-1.13: command not found
make: *** [Makefile:291: Makefile.in] Error 1

Please advise. Thank you very much for your help.

Rong Yao

**Comment by ryao-mdanderson** [comment]
@drpowell thank you for review my issue report.

**Comment by drpowell** [comment]
We are not the authors of this tool.  
This is just a fork of the original to allow us to fix a issue we found.
We cannot provide support for this tool.
